// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA29mA6NliHqi3eHhtCLaZSsVK0YjuRuC8',
    appId: '1:690923108196:web:9bdfcf5aff0a3d7712ac71',
    messagingSenderId: '690923108196',
    projectId: 'capitalholdingco-ac8ad',
    authDomain: 'capitalholdingco-ac8ad.firebaseapp.com',
    databaseURL: 'https://capitalholdingco-ac8ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capitalholdingco-ac8ad.appspot.com',
    measurementId: 'G-9LWERX6S5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Da2svFQBFac4octHaduGVsCRdJSRFmc',
    appId: '1:690923108196:android:7aa464e987e64a7012ac71',
    messagingSenderId: '690923108196',
    projectId: 'capitalholdingco-ac8ad',
    databaseURL: 'https://capitalholdingco-ac8ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capitalholdingco-ac8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZUV-gQ3fFqTlMm_9DDdIrCu365QjGSI',
    appId: '1:690923108196:ios:0a19462b991557e512ac71',
    messagingSenderId: '690923108196',
    projectId: 'capitalholdingco-ac8ad',
    databaseURL: 'https://capitalholdingco-ac8ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capitalholdingco-ac8ad.appspot.com',
    androidClientId: '690923108196-44bg3nrc4svut8362quugqotf4ojkk0e.apps.googleusercontent.com',
    iosClientId: '690923108196-evv2a1td3o13sv8trsle1f88a0kteagl.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelanceproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyZUV-gQ3fFqTlMm_9DDdIrCu365QjGSI',
    appId: '1:690923108196:ios:0a19462b991557e512ac71',
    messagingSenderId: '690923108196',
    projectId: 'capitalholdingco-ac8ad',
    databaseURL: 'https://capitalholdingco-ac8ad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capitalholdingco-ac8ad.appspot.com',
    androidClientId: '690923108196-44bg3nrc4svut8362quugqotf4ojkk0e.apps.googleusercontent.com',
    iosClientId: '690923108196-evv2a1td3o13sv8trsle1f88a0kteagl.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelanceproject',
  );
}
